# .github/workflows/test.yml

name: Test
on: push  # Trigger on push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-16.04 # Specific version for Cypress

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '2.6' # Specify your version
    - name: Cache gems # You can cache your gems to make the workflow run faster
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Start server in the background
      run: |
        bundle exec rails server &
        sleep 5 && 
        curl http://localhost:3000 -I

    # Add step for running cucumber tests here
    
    - name: Run Cypress
      uses: cypress-io/github-action@v1
      with:
        browser: chrome
        headless: true
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - name: Upload videos as artifacts
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
